dist: xenial
language: python
cache: pip
python:
  - "3.8"
env:
  global:
  - DOCKERHUB_PROJECT=safe-relay-service
  - SOURCE_FOLDER=safe_relay_service
  - PIP_USE_MIRRORS=true
  - DJANGO_SETTINGS_MODULE=config.settings.test
  - DATABASE_URL=psql://postgres@localhost/travisci
  - ETHEREUM_NODE_URL=http://localhost:8545
addons:
  postgresql: "9.6"
services:
  - docker
  - postgresql
  - redis-server
install:
  - npm install -g ganache-cli@6.6.0 && ganache-cli -d -p 8545 --defaultBalanceEther 10000 --gasLimit 10000000 -a 30 --noVMErrorsOnRPCResponse > /dev/null &
  - travis_retry pip install -r requirements-test.txt
  - travis_retry pip install coveralls
before_script:
  - psql -c 'create database travisci;' -U postgres
script:
  - coverage run --source=$SOURCE_FOLDER -m py.test -rxXs
deploy:
  - provider: script
    script: bash scripts/deploy_docker.sh staging
    on:
      branch: master
  - provider: script
    script: bash scripts/deploy_docker.sh develop
    on:
      branch: develop
  - provider: script
    script: bash scripts/deploy_docker.sh $TRAVIS_TAG
    on:
      tags: true
after_success:
  - coveralls
