version: '3.5'

services:
  web:
    build:
      context: .
      dockerfile: docker/web/Dockerfile
    env_file:
      - .env_ganache
    depends_on:
      - db
      - redis
    working_dir: /app
    ports:
      - "8888:8888"
    volumes:
      - nginx-shared:/nginx
    command: docker/web/run_web.sh

  worker: &worker
    build:
      context: .
      dockerfile: docker/web/Dockerfile
    env_file:
      - .env_ganache
    depends_on:
      - db
      - redis
    command: docker/web/celery/worker/run.sh

  ganache:
    build:
      context: .
      dockerfile: docker/ganache/Dockerfile
    ports:
      - "8545:8545"
