version: '3.5'

volumes:
  nginx-shared:

services:
  db:
    image: postgres:10-alpine
    ports:
      - "5432:5432"
  redis:
    image: redis:4-alpine
    ports:
      - "6379:6379"

  worker: &worker
    build:
      context: .
      dockerfile: docker/web/Dockerfile
    env_file:
      - .env
    depends_on:
      - db
      - redis
      - ganache
    command: docker/web/celery/worker/run.sh

  scheduler:
    <<: *worker
    command: docker/web/celery/scheduler/run.sh

  ganache:
    build:
      context: .
      dockerfile: docker/ganache/Dockerfile
    ports:
      - "8545:8545"
