# Generated by Django 2.1.3 on 2018-11-14 12:32

import django_eth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relay', '0002_safemultisigtx_refund_receiver'),
    ]

    operations = [
        migrations.AddField(
            model_name='safecreation',
            name='payment_token',
            field=django_eth.models.EthereumAddressField(null=True),
        ),
    ]
