# Generated by Django 2.1.3 on 2018-11-20 12:48

from django.db import migrations

import gnosis.eth.django.models


class Migration(migrations.Migration):

    dependencies = [
        ("relay", "0004_safecreation_payment_ether"),
    ]

    operations = [
        migrations.AddField(
            model_name="safecreation",
            name="funder",
            field=gnosis.eth.django.models.EthereumAddressField(null=True),
        ),
    ]
