# Generated by Django 2.1.3 on 2019-01-10 19:41

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_eth.models
import model_utils.fields

class Migration(migrations.Migration):

    dependencies = [
        ('relay', '0005_safecreation_funder'),
    ]

    operations = [
        migrations.CreateModel(
            name='SafeMultisigSubTx',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('to', django_eth.models.EthereumAddressField(null=True)),
                ('value', django_eth.models.Uint256Field()),
                ('data', models.BinaryField(null=True)),
                ('operation', models.PositiveSmallIntegerField(choices=[(0, 'CALL'), (1, 'DELEGATE_CALL'), (2, 'CREATE')])),
                ('safe_tx_gas', django_eth.models.Uint256Field()),
                ('data_gas', django_eth.models.Uint256Field()),
                ('gas_price', django_eth.models.Uint256Field()),
                ('gas_token', django_eth.models.EthereumAddressField(null=True)),
                ('refund_receiver', django_eth.models.EthereumAddressField(null=True)),
                ('signatures', models.BinaryField()),
                ('gas', django_eth.models.Uint256Field()),
                ('nonce', django_eth.models.Uint256Field()),
                ('tx_hash', django_eth.models.Sha3HashField(unique=True)),
                ('tx_mined', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='safecontract',
            name='salt',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='safecontract',
            name='subscription_module_address',
            field=django_eth.models.EthereumAddressField(null=True),
        ),
        migrations.AlterField(
            model_name='safecontract',
            name='address',
            field=django_eth.models.EthereumAddressField(null=True),
        ),
        migrations.AddField(
            model_name='safemultisigsubtx',
            name='safe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='relay.SafeContract'),
        ),
        migrations.AlterUniqueTogether(
            name='safemultisigsubtx',
            unique_together={('safe', 'nonce')},
        ),
    ]