# Generated by Django 2.1.4 on 2018-12-20 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("relay", "0005_safecreation_funder"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="safecreation",
            name="payment_ether",
        ),
    ]
