# Generated by Django 2.1.7 on 2019-04-01 11:56

from django.db import migrations, models
import django.db.models.deletion


def populate_ethereum_tx_foreign_key(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    SafeMultisigTx = apps.get_model('relay', 'SafeMultisigTx')
    for safe_multisig_tx in SafeMultisigTx.objects.all():
        safe_multisig_tx.ethereum_tx = safe_multisig_tx.tx_hash
        safe_multisig_tx.save()


class Migration(migrations.Migration):

    dependencies = [
        ('relay', '0011_populate_ethereumtx'),
    ]

    operations = [
        migrations.AddField(
            model_name='safemultisigtx',
            name='ethereum_tx',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='relay.EthereumTx'),
        ),
        migrations.RunPython(populate_ethereum_tx_foreign_key),
        migrations.AlterField(
            model_name='safemultisigtx',
            name='ethereum_tx',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='relay.EthereumTx'),
        )
    ]
