# Generated by Django 2.2 on 2019-04-24 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("relay", "0015_ethereumtx_gas_used"),
    ]

    operations = [
        migrations.AddField(
            model_name="internaltx",
            name="error",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
