# Generated by Django 2.2.1 on 2019-05-14 12:11

from django.db import migrations

import gnosis.eth.django.models


class Migration(migrations.Migration):

    dependencies = [
        ("relay", "0019_ethereumevent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ethereumtx",
            name="_from",
            field=gnosis.eth.django.models.EthereumAddressField(
                db_index=True, null=True
            ),
        ),
        migrations.AlterField(
            model_name="ethereumtx",
            name="to",
            field=gnosis.eth.django.models.EthereumAddressField(
                db_index=True, null=True
            ),
        ),
        migrations.AlterField(
            model_name="internaltx",
            name="_from",
            field=gnosis.eth.django.models.EthereumAddressField(db_index=True),
        ),
        migrations.AlterField(
            model_name="internaltx",
            name="contract_address",
            field=gnosis.eth.django.models.EthereumAddressField(
                db_index=True, null=True
            ),
        ),
        migrations.AlterField(
            model_name="internaltx",
            name="to",
            field=gnosis.eth.django.models.EthereumAddressField(
                db_index=True, null=True
            ),
        ),
        migrations.AlterField(
            model_name="safemultisigtx",
            name="to",
            field=gnosis.eth.django.models.EthereumAddressField(
                db_index=True, null=True
            ),
        ),
    ]
