# Generated by Django 2.2.1 on 2019-05-27 09:14

import django.db.models.deletion
from django.db import migrations, models

import gnosis.eth.django.models


class Migration(migrations.Migration):

    dependencies = [
        ("relay", "0020_auto_20190514_1211"),
    ]

    operations = [
        migrations.CreateModel(
            name="EthereumBlock",
            fields=[
                (
                    "number",
                    models.PositiveIntegerField(
                        primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("gas_limit", models.PositiveIntegerField()),
                ("gas_used", models.PositiveIntegerField()),
                ("timestamp", models.DateTimeField()),
                ("block_hash", gnosis.eth.django.models.Sha3HashField(unique=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name="safecreation2",
            options={"verbose_name_plural": "Safe creation2s"},
        ),
        migrations.AlterModelOptions(
            name="safetxstatus",
            options={"verbose_name_plural": "Safe tx status"},
        ),
        migrations.RemoveField(
            model_name="ethereumtx",
            name="block_number",
        ),
        migrations.AddField(
            model_name="ethereumtx",
            name="block",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="txs",
                to="relay.EthereumBlock",
            ),
        ),
    ]
