# Generated by Django 2.2.2 on 2019-06-12 15:39

import django.utils.timezone
from django.db import migrations

import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ("relay", "0022_auto_20190606_1224"),
    ]

    operations = [
        migrations.AddField(
            model_name="ethereumtx",
            name="created",
            field=model_utils.fields.AutoCreatedField(
                default=django.utils.timezone.now,
                editable=False,
                verbose_name="created",
            ),
        ),
        migrations.AddField(
            model_name="ethereumtx",
            name="modified",
            field=model_utils.fields.AutoLastModifiedField(
                default=django.utils.timezone.now,
                editable=False,
                verbose_name="modified",
            ),
        ),
    ]
