# Generated by Django 3.0.3 on 2020-02-04 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("relay", "0023_auto_20190612_1539"),
    ]

    operations = [
        migrations.DeleteModel(
            name="InternalTx",
        ),
    ]
