# Generated by Django 3.0.7 on 2020-06-26 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("relay", "0025_auto_20200429_1101"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="safemultisigtx",
            unique_together=set(),
        ),
    ]
