# Generated by Django 3.2.9 on 2021-11-19 15:41

from django.db import migrations

import gnosis.eth.django.models


class Migration(migrations.Migration):

    dependencies = [
        ("relay", "0030_auto_20210610_1502"),
    ]

    operations = [
        migrations.AddField(
            model_name="ethereumtx",
            name="max_fee_per_gas",
            field=gnosis.eth.django.models.Uint256Field(default=0),
        ),
        migrations.AddField(
            model_name="ethereumtx",
            name="max_priority_fee_per_gas",
            field=gnosis.eth.django.models.Uint256Field(default=0),
        ),
    ]
