# Generated by Django 2.0.5 on 2018-05-29 11:07

import django.utils.timezone
from django.db import migrations, models

import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GasPrice",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("lowest", models.BigIntegerField()),
                ("safe_low", models.BigIntegerField()),
                ("standard", models.BigIntegerField()),
                ("fast", models.BigIntegerField()),
                ("fastest", models.BigIntegerField()),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
