# Generated by Django 2.0.5 on 2018-06-04 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gas_station", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="gasprice",
            options={"get_latest_by": "created"},
        ),
    ]
