# Generated by Django 2.1.3 on 2018-11-14 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tokens", "0003_token_relevance"),
    ]

    operations = [
        migrations.RenameField(
            model_name="token",
            old_name="code",
            new_name="symbol",
        ),
    ]
