# Generated by Django 2.1.3 on 2018-12-12 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tokens", "0007_auto_20181205_1024"),
    ]

    operations = [
        migrations.AddField(
            model_name="priceoracleticker",
            name="inverse",
            field=models.BooleanField(default=False),
        ),
    ]
