# Generated by Django 2.1.7 on 2019-02-25 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tokens", "0010_auto_20190124_1709"),
    ]

    operations = [
        migrations.AlterField(
            model_name="token",
            name="relevance",
            field=models.PositiveIntegerField(default=100),
        ),
    ]
