# Generated by Django 2.2.7 on 2019-11-22 15:07

import django.contrib.postgres.fields.jsonb
from django.db import migrations


def create_uniswap_price_oracle(apps, schema_editor):
    PriceOracle = apps.get_model('tokens', 'PriceOracle')
    # Use uniswap mainnet address
    PriceOracle.objects.create(name='Uniswap', configuration={'uniswap_exchange_address':
                                                              '0xc0a47dFe034B400B47bDaD5FecDa2621de6c4d95'})


class Migration(migrations.Migration):

    dependencies = [
        ('tokens', '0011_auto_20190225_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='priceoracle',
            name='configuration',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
        migrations.RunPython(create_uniswap_price_oracle)
    ]
