# Generated by Django 3.1.2 on 2020-11-02 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tokens", "0013_auto_20200217_0942"),
    ]

    operations = [
        migrations.AlterField(
            model_name="priceoracle",
            name="configuration",
            field=models.JSONField(default=dict),
        ),
    ]
