# Generated by Django 2.0.6 on 2018-06-05 14:57

import django.contrib.postgres.fields
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models

import safe_relay_service.safe.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SafeContract',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('address', safe_relay_service.safe.models.EthereumAddressField(primary_key=True, serialize=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SafeCreation',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('deployer', safe_relay_service.safe.models.EthereumAddressField(primary_key=True, serialize=False)),
                ('owners', django.contrib.postgres.fields.ArrayField(base_field=safe_relay_service.safe.models.EthereumAddressField(), size=None)),
                ('threshold', models.PositiveSmallIntegerField()),
                ('signed_tx', models.BinaryField()),
                ('tx_hash', models.CharField(max_length=64, unique=True)),
                ('gas', models.PositiveIntegerField()),
                ('gas_price', models.BigIntegerField()),
                ('v', models.PositiveSmallIntegerField()),
                ('r', safe_relay_service.safe.models.EthereumBigIntegerField(max_length=64)),
                ('s', safe_relay_service.safe.models.EthereumBigIntegerField(max_length=64)),
                ('safe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='safe.SafeContract')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
