# Generated by Django 2.0.6 on 2018-06-08 15:43

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safe', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SafeFunding',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('safe', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='safe.SafeContract')),
                ('safe_funded', models.BooleanField(default=False)),
                ('deployer_funded', models.BooleanField(db_index=True, default=False)),
                ('deployer_funded_tx_hash', models.CharField(max_length=64, unique=True)),
                ('safe_deployed', models.BooleanField(db_index=True, default=False)),
                ('safe_deployed_tx_hash', models.CharField(max_length=64, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='safecreation',
            name='safe',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='safe.SafeContract'),
        ),
    ]
