# Generated by Django 2.0.6 on 2018-06-14 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safe', '0002_auto_20180608_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='safefunding',
            name='deployer_funded_tx_hash',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='safefunding',
            name='safe_deployed_tx_hash',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
