# Generated by Django 2.0.6 on 2018-06-14 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safe', '0003_auto_20180614_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='safecreation',
            name='data',
            field=models.BinaryField(null=True),
        ),
        migrations.AddField(
            model_name='safecreation',
            name='payment',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='safecreation',
            name='value',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='safecreation',
            name='signed_tx',
            field=models.BinaryField(null=True),
        ),
    ]
