# Generated by Django 2.0.7 on 2018-07-09 10:29

from django.db import migrations, models
from hexbytes import HexBytes


def forwards_func(apps, schema_editor):
    SafeFunding = apps.get_model("safe", "SafeFunding")
    db_alias = schema_editor.connection.alias
    for safe_funding in SafeFunding.objects.using(db_alias).all():
        if safe_funding.deployer_funded_tx_hash:
            safe_funding.deployer_funded_tx_hash = HexBytes(safe_funding.deployer_funded_tx_hash).hex()
        if safe_funding.safe_deployed_tx_hash:
            safe_funding.safe_deployed_tx_hash = HexBytes(safe_funding.safe_deployed_tx_hash).hex()
        safe_funding.save()


def reverse_func(apps, schema_editor):
    SafeFunding = apps.get_model("safe", "SafeFunding")
    db_alias = schema_editor.connection.alias
    for safe_funding in SafeFunding.objects.using(db_alias).all():
        if safe_funding.deployer_funded_tx_hash:
            safe_funding.deployer_funded_tx_hash = HexBytes(safe_funding.deployer_funded_tx_hash).hex()[2:]
        if safe_funding.safe_deployed_tx_hash:
            safe_funding.safe_deployed_tx_hash = HexBytes(safe_funding.safe_deployed_tx_hash).hex()[2:]
        safe_funding.save()


class Migration(migrations.Migration):

    dependencies = [
        ('safe', '0006_safemultisigtx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='safefunding',
            name='deployer_funded_tx_hash',
            field=models.CharField(blank=True, max_length=66, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='safefunding',
            name='safe_deployed_tx_hash',
            field=models.CharField(blank=True, max_length=66, null=True, unique=True),
        ),
        migrations.RunPython(forwards_func, reverse_func),
    ]
