# Generated by Django 2.0.7 on 2018-07-23 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('safe', '0007_auto_20180709_1113'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='safemultisigtx',
            unique_together={('safe', 'nonce')},
        ),
    ]
