# Generated by Django 2.0.8 on 2018-08-10 10:47

from django.db import migrations
import django_eth.models


class Migration(migrations.Migration):

    dependencies = [
        ('safe', '0008_auto_20180723_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='safecreation',
            name='gas',
            field=django_eth.models.Uint256Field(),
        ),
        migrations.AlterField(
            model_name='safecreation',
            name='gas_price',
            field=django_eth.models.Uint256Field(),
        ),
        migrations.AlterField(
            model_name='safecreation',
            name='payment',
            field=django_eth.models.Uint256Field(),
        ),
        migrations.AlterField(
            model_name='safecreation',
            name='threshold',
            field=django_eth.models.Uint256Field(),
        ),
        migrations.AlterField(
            model_name='safecreation',
            name='value',
            field=django_eth.models.Uint256Field(),
        ),
        migrations.AlterField(
            model_name='safemultisigtx',
            name='data_gas',
            field=django_eth.models.Uint256Field(),
        ),
        migrations.AlterField(
            model_name='safemultisigtx',
            name='gas',
            field=django_eth.models.Uint256Field(),
        ),
        migrations.AlterField(
            model_name='safemultisigtx',
            name='gas_price',
            field=django_eth.models.Uint256Field(),
        ),
        migrations.AlterField(
            model_name='safemultisigtx',
            name='nonce',
            field=django_eth.models.Uint256Field(),
        ),
        migrations.AlterField(
            model_name='safemultisigtx',
            name='safe_tx_gas',
            field=django_eth.models.Uint256Field(),
        ),
        migrations.AlterField(
            model_name='safemultisigtx',
            name='value',
            field=django_eth.models.Uint256Field(),
        ),
    ]
