# Generated by Django 2.0.8 on 2018-08-10 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safe', '0009_auto_20180810_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='safecreation',
            name='r',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='safecreation',
            name='s',
            field=models.CharField(max_length=100),
        ),
    ]
