# Generated by Django 2.0.8 on 2018-08-10 11:19

from django.db import migrations
import django_eth.models


def forwards_func(apps, schema_editor):
    SafeCreation = apps.get_model("safe", "SafeCreation")
    db_alias = schema_editor.connection.alias
    for safe_creation in SafeCreation.objects.using(db_alias).all():
        safe_creation.r = str(safe_creation.r)
        safe_creation.s = str(safe_creation.s)
        safe_creation.save()


def reverse_func(apps, schema_editor):
    SafeCreation = apps.get_model("safe", "SafeCreation")
    db_alias = schema_editor.connection.alias
    for safe_creation in SafeCreation.objects.using(db_alias).all():
        safe_creation.r = hex(int(str(safe_creation.r)))[2:]
        safe_creation.s = hex(int(str(safe_creation.s)))[2:]
        safe_creation.save()


class Migration(migrations.Migration):

    dependencies = [
        ('safe', '0010_auto_20180810_1201'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
        migrations.AlterField(
            model_name='safecreation',
            name='r',
            field=django_eth.models.Uint256Field(),
        ),
        migrations.AlterField(
            model_name='safecreation',
            name='s',
            field=django_eth.models.Uint256Field(),
        ),
    ]
