# Generated by Django 2.0.8 on 2018-08-13 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safe', '0010_auto_20180813_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='safemultisigtx',
            name='operation',
            field=models.PositiveSmallIntegerField(choices=[(0, 'CALL'), (1, 'DELEGATE_CALL'), (2, 'CREATE')]),
        ),
    ]
